jupyterhub:
  # https: false must be specified for initial deployment to work!
  # proxy:
  #    https:
  #      enabled: false
  prePuller:
    continuous:
      enabled: true
  singleuser:
    defaultUrl: "/rstudio"
#    serviceAccountName: jovyan #must create separately, otherwise use 'default'
    startTimeout: 600
    cpu:
      limit: 2
      guarantee: 1
    memory:
      limit: 8G
      guarantee: 7G
    image:
      name: eicompare/jhub-rstudio
      tag: latest
    initContainers:
      - name: mount-shared-folder
        image: busybox
        command:
          - "sh"
          - "-c"
          - >
            id && chown 1000:1000 /srv/shared && ls -lhd /srv/shared ;
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: jupyterhub-shared
            mountPath: /srv/shared
            subPath: "dssg.hackweek.io/shared"
    storage:
      dynamic:
        storageClass: aws-efs
      extraVolumeMounts:
        - name: jupyterhub-shared
          mountPath: /srv/shared
          subPath: "dssg.hackweek.io/shared"
        # - name: singleuser-scratch
        #   mountPath: /srv/scratch
      extraVolumes:
        - name: jupyterhub-shared
          persistentVolumeClaim:
            claimName: shared-nfs
        # - name: singleuser-scratch
        #   persistentVolumeClaim:
        #     claimName: scratch-ebs
    lifecycleHooks:
      postStart:
        exec:
          command:
            - "sh"
            - "-c"
            - >
              test -L /home/jovyan/shared || ln -s /srv/shared /home/jovyan/shared

  # automatically terminate pods after 12 hours 
  cull:
    maxAge: 43200  
  
  auth:
    type: custom
    custom:
      className: oauthenticator.generic.GenericOAuthenticator
      config:
        login_service: "Auth0"
        token_url: https://uwhackweeks.auth0.com/oauth/token
        userdata_url: https://uwhackweeks.auth0.com/oauth/userinfo
        userdata_method: GET
        username_key: nickname
        scope:
          - openid
          - profile
          - email
    admin:
      access: true
      users:
        - scottyhq
        - salvis2
  hub:
    resources:
      requests:
        cpu: 0.5
        memory: 1G
      limits:
        cpu: 1.5
        memory: 2G
    initContainers:
      - name: git-clone-templates
        image: alpine/git
        args:
          - clone
          - --single-branch
          - --branch=master
          - --depth=1
          - --
          - https://github.com/scottyhq/dssg-jhub-templates.git
          - /etc/jupyterhub/custom
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: custom-templates
            mountPath: /etc/jupyterhub/custom
    extraVolumes:
      - name: custom-templates
        emptyDir: {}
    extraVolumeMounts:
      - name: custom-templates
        mountPath: /etc/jupyterhub/custom
    extraConfig:
      00-templates: |
        c.JupyterHub.template_paths = ['/etc/jupyterhub/custom/templates']
      01-spawner-config: |
        c.Spawner.cmd = ['jupyter-labhub']
# disable for now to allow switching between /lab and /rstudio
#      01-hub-config: |
#        c.JupyterHub.shutdown_on_logout = True
    extraEnv:
      OAUTH2_AUTHORIZE_URL: "https://uwhackweeks.auth0.com/authorize"
      OAUTH2_TOKEN_URL: "https://uwhackweeks.auth0.com/oauth/token"
