jupyterhub:
  proxy:
    https:
      enabled: true
      hosts:
        - dssg.hackweek.io
      letsencrypt:
        contactEmail: scottyh@uw.edu
  hub:
    extraEnv:
      OAUTH_CALLBACK_URL: "https://dssg.hackweek.io/hub/oauth_callback"
