jupyterhub:
  proxy:
    https:
      enabled: true
      hosts:
        - staging.dssg.hackweek.io
      letsencrypt:
        contactEmail: scottyh@uw.edu
  hub:
    resources:
      requests:
        cpu: 0
        memory: 0
      limits:
        cpu: 0.5
        memory: 1G
    extraEnv:
      OAUTH_CALLBACK_URL: "https://staging.dssg.hackweek.io/hub/oauth_callback"
